version: '3.8'

services:
  fanx:
    image: realswaggymacro/fanx:latest
    container_name: fanx
    ports:
      - "5136:5136"
    volumes:
      - /docker/fanX/data:/app/data
      - /docker/fanX/logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - FanX_PORT=5136
    restart: unless-stopped
