//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FanX.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FanX.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Condition.
        /// </summary>
        internal static string AddCondition {
            get {
                return ResourceManager.GetString("AddCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Condition.
        /// </summary>
        internal static string AddConditionTitle {
            get {
                return ResourceManager.GetString("AddConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Rule.
        /// </summary>
        internal static string AddNewRule {
            get {
                return ResourceManager.GetString("AddNewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Rule.
        /// </summary>
        internal static string AddRule {
            get {
                return ResourceManager.GetString("AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Rule.
        /// </summary>
        internal static string AddRuleTitle {
            get {
                return ResourceManager.GetString("AddRuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user failed..
        /// </summary>
        internal static string AddUserFailed {
            get {
                return ResourceManager.GetString("AddUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user success..
        /// </summary>
        internal static string AddUserSuccess {
            get {
                return ResourceManager.GetString("AddUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Registration.
        /// </summary>
        internal static string AllowRegistration {
            get {
                return ResourceManager.GetString("AllowRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FanX.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic (System Default).
        /// </summary>
        internal static string AutomaticSystemDefault {
            get {
                return ResourceManager.GetString("AutomaticSystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password..
        /// </summary>
        internal static string ChangePasswordFailed {
            get {
                return ResourceManager.GetString("ChangePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Fan.
        /// </summary>
        internal static string ChooseFan {
            get {
                return ResourceManager.GetString("ChooseFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Logs.
        /// </summary>
        internal static string ClearLogs {
            get {
                return ResourceManager.GetString("ClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Sensor Data.
        /// </summary>
        internal static string ClearSensorData {
            get {
                return ResourceManager.GetString("ClearSensorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command failed.
        /// </summary>
        internal static string CommandFailed {
            get {
                return ResourceManager.GetString("CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command successful.
        /// </summary>
        internal static string CommandSuccessful {
            get {
                return ResourceManager.GetString("CommandSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        internal static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All conditions must be met for the rule to trigger..
        /// </summary>
        internal static string ConditionsHelpText {
            get {
                return ResourceManager.GetString("ConditionsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Action.
        /// </summary>
        internal static string ConfirmAction {
            get {
                return ResourceManager.GetString("ConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to perform the action: &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmActionMessage {
            get {
                return ResourceManager.GetString("ConfirmActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this rule?.
        /// </summary>
        internal static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user? This cannot be undone..
        /// </summary>
        internal static string ConfirmDeleteUserMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User Confirmation.
        /// </summary>
        internal static string ConfirmDeleteUserTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        internal static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirmation do not match..
        /// </summary>
        internal static string ConfirmPasswordMismatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control All Fan.
        /// </summary>
        internal static string ControlAllFan {
            get {
                return ResourceManager.GetString("ControlAllFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Single Fan.
        /// </summary>
        internal static string ControlSingleFan {
            get {
                return ResourceManager.GetString("ControlSingleFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooldown (Mins).
        /// </summary>
        internal static string CooldownMins {
            get {
                return ResourceManager.GetString("CooldownMins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU1 Temp.
        /// </summary>
        internal static string Cpu1Temp {
            get {
                return ResourceManager.GetString("Cpu1Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU1 Temp (°C).
        /// </summary>
        internal static string Cpu1TempThresholdLabel {
            get {
                return ResourceManager.GetString("Cpu1TempThresholdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU2 Temp.
        /// </summary>
        internal static string Cpu2Temp {
            get {
                return ResourceManager.GetString("Cpu2Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU2 Temp (°C).
        /// </summary>
        internal static string Cpu2TempThresholdLabel {
            get {
                return ResourceManager.GetString("Cpu2TempThresholdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Tools.
        /// </summary>
        internal static string DebugTools {
            get {
                return ResourceManager.GetString("DebugTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this rule? This process cannot be undone..
        /// </summary>
        internal static string DeleteRuleConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteRuleConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        internal static string DeleteRuleConfirmTitle {
            get {
                return ResourceManager.GetString("DeleteRuleConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete user..
        /// </summary>
        internal static string DeleteUserFailed {
            get {
                return ResourceManager.GetString("DeleteUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully..
        /// </summary>
        internal static string DeleteUserSuccess {
            get {
                return ResourceManager.GetString("DeleteUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demote to User.
        /// </summary>
        internal static string DemoteToUser {
            get {
                return ResourceManager.GetString("DemoteToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Log.
        /// </summary>
        internal static string DownloadLog {
            get {
                return ResourceManager.GetString("DownloadLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit condition.
        /// </summary>
        internal static string EditConditionTitle {
            get {
                return ResourceManager.GetString("EditConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit rule.
        /// </summary>
        internal static string EditRule {
            get {
                return ResourceManager.GetString("EditRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Recipients.
        /// </summary>
        internal static string EmailRecipients {
            get {
                return ResourceManager.GetString("EmailRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Settings.
        /// </summary>
        internal static string EmailSettings {
            get {
                return ResourceManager.GetString("EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto Control.
        /// </summary>
        internal static string EnableAutoControl {
            get {
                return ResourceManager.GetString("EnableAutoControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Email Notifications.
        /// </summary>
        internal static string EnableEmailNotifications {
            get {
                return ResourceManager.GetString("EnableEmailNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Manual Control.
        /// </summary>
        internal static string EnableManualControl {
            get {
                return ResourceManager.GetString("EnableManualControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Notifications.
        /// </summary>
        internal static string EnableNotifications {
            get {
                return ResourceManager.GetString("EnableNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Ssl.
        /// </summary>
        internal static string EnableSsl {
            get {
                return ResourceManager.GetString("EnableSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Telegram Bot.
        /// </summary>
        internal static string EnableTelegramBot {
            get {
                return ResourceManager.GetString("EnableTelegramBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Webhook.
        /// </summary>
        internal static string EnableWebhook {
            get {
                return ResourceManager.GetString("EnableWebhook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable WeCom Bot.
        /// </summary>
        internal static string EnableWeComBot {
            get {
                return ResourceManager.GetString("EnableWeComBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading log files: {0}.
        /// </summary>
        internal static string ErrorLoadingLogFiles {
            get {
                return ResourceManager.GetString("ErrorLoadingLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading log file: {0}.
        /// </summary>
        internal static string ErrorReadingLogFile {
            get {
                return ResourceManager.GetString("ErrorReadingLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhaust Temp.
        /// </summary>
        internal static string ExhaustTemp {
            get {
                return ResourceManager.GetString("ExhaustTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhaust Temp (°C).
        /// </summary>
        internal static string ExhaustTempThresholdLabel {
            get {
                return ResourceManager.GetString("ExhaustTempThresholdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load sensor list.
        /// </summary>
        internal static string FailedToLoadSensorList {
            get {
                return ResourceManager.GetString("FailedToLoadSensorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Control.
        /// </summary>
        internal static string FanControl {
            get {
                return ResourceManager.GetString("FanControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Control Mode.
        /// </summary>
        internal static string FanControlMode {
            get {
                return ResourceManager.GetString("FanControlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Control Settings.
        /// </summary>
        internal static string FanControlSettings {
            get {
                return ResourceManager.GetString("FanControlSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Debug.
        /// </summary>
        internal static string FanDebug {
            get {
                return ResourceManager.GetString("FanDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fans.
        /// </summary>
        internal static string Fans {
            get {
                return ResourceManager.GetString("Fans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan sensor not found.
        /// </summary>
        internal static string FanSensorNotFound {
            get {
                return ResourceManager.GetString("FanSensorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Speed.
        /// </summary>
        internal static string FanSpeed {
            get {
                return ResourceManager.GetString("FanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Speed History.
        /// </summary>
        internal static string FanSpeedHistory {
            get {
                return ResourceManager.GetString("FanSpeedHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Speed (%).
        /// </summary>
        internal static string FanSpeedPercentLabel {
            get {
                return ResourceManager.GetString("FanSpeedPercentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {0} speed to {1}%.
        /// </summary>
        internal static string FanSpeedSetTo {
            get {
                return ResourceManager.GetString("FanSpeedSetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix validation errors..
        /// </summary>
        internal static string FixValidationErrors {
            get {
                return ResourceManager.GetString("FixValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Fan Speed.
        /// </summary>
        internal static string GetFanSpeed {
            get {
                return ResourceManager.GetString("GetFanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Full SDR List.
        /// </summary>
        internal static string GetFullSdrList {
            get {
                return ResourceManager.GetString("GetFullSdrList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get SDR List.
        /// </summary>
        internal static string GetSdrList {
            get {
                return ResourceManager.GetString("GetSdrList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Sensor List.
        /// </summary>
        internal static string GetSensorList {
            get {
                return ResourceManager.GetString("GetSensorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Home.
        /// </summary>
        internal static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? Login now.
        /// </summary>
        internal static string HasAccount {
            get {
                return ResourceManager.GetString("HasAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname or IP Address.
        /// </summary>
        internal static string HostnameOrIpAddress {
            get {
                return ResourceManager.GetString("HostnameOrIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlet Temp.
        /// </summary>
        internal static string InletTemp {
            get {
                return ResourceManager.GetString("InletTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlet Temp (°C).
        /// </summary>
        internal static string InletTempThresholdLabel {
            get {
                return ResourceManager.GetString("InletTempThresholdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Chosen Fan.
        /// </summary>
        internal static string InvalidChosenFan {
            get {
                return ResourceManager.GetString("InvalidChosenFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPMI Config.
        /// </summary>
        internal static string IpmiConfiguration {
            get {
                return ResourceManager.GetString("IpmiConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPMI Control.
        /// </summary>
        internal static string IpmiControl {
            get {
                return ResourceManager.GetString("IpmiControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPMI Diagnostics.
        /// </summary>
        internal static string IpmiDiagnostics {
            get {
                return ResourceManager.GetString("IpmiDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last {0} Days.
        /// </summary>
        internal static string LastDays {
            get {
                return ResourceManager.GetString("LastDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last {0} Hours.
        /// </summary>
        internal static string LastHours {
            get {
                return ResourceManager.GetString("LastHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log directory not found..
        /// </summary>
        internal static string LogDirectoryNotFound {
            get {
                return ResourceManager.GetString("LogDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        internal static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Now.
        /// </summary>
        internal static string LoginNow {
            get {
                return ResourceManager.GetString("LoginNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful!.
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Retention (Days).
        /// </summary>
        internal static string LogRetentionDays {
            get {
                return ResourceManager.GetString("LogRetentionDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Viewer.
        /// </summary>
        internal static string LogViewer {
            get {
                return ResourceManager.GetString("LogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string ManualMode {
            get {
                return ResourceManager.GetString("ManualMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Template.
        /// </summary>
        internal static string MessageTemplate {
            get {
                return ResourceManager.GetString("MessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Register now.
        /// </summary>
        internal static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conditions added yet. Add at least one condition to make the rule active..
        /// </summary>
        internal static string NoConditions {
            get {
                return ResourceManager.GetString("NoConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Rules.
        /// </summary>
        internal static string NotificationRules {
            get {
                return ResourceManager.GetString("NotificationRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Settings.
        /// </summary>
        internal static string NotificationSettings {
            get {
                return ResourceManager.GetString("NotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged in. Please login to access more features..
        /// </summary>
        internal static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Test Dialog.
        /// </summary>
        internal static string OpenTestDialog {
            get {
                return ResourceManager.GetString("OpenTestDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal To.
        /// </summary>
        internal static string OperatorEqualTo {
            get {
                return ResourceManager.GetString("OperatorEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than.
        /// </summary>
        internal static string OperatorGreaterThan {
            get {
                return ResourceManager.GetString("OperatorGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than.
        /// </summary>
        internal static string OperatorLessThan {
            get {
                return ResourceManager.GetString("OperatorLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output:.
        /// </summary>
        internal static string OutputLabel {
            get {
                return ResourceManager.GetString("OutputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        internal static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the page you are looking for does not exist..
        /// </summary>
        internal static string PageNotFoundMessage {
            get {
                return ResourceManager.GetString("PageNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a fan.
        /// </summary>
        internal static string PleaseChooseAFan {
            get {
                return ResourceManager.GetString("PleaseChooseAFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Consumption.
        /// </summary>
        internal static string PowerConsumption {
            get {
                return ResourceManager.GetString("PowerConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Cycle.
        /// </summary>
        internal static string PowerCycle {
            get {
                return ResourceManager.GetString("PowerCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power History.
        /// </summary>
        internal static string PowerHistory {
            get {
                return ResourceManager.GetString("PowerHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Off.
        /// </summary>
        internal static string PowerOff {
            get {
                return ResourceManager.GetString("PowerOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power On.
        /// </summary>
        internal static string PowerOn {
            get {
                return ResourceManager.GetString("PowerOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Status.
        /// </summary>
        internal static string PowerStatus {
            get {
                return ResourceManager.GetString("PowerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can view and edit your profile..
        /// </summary>
        internal static string ProfileDescription {
            get {
                return ResourceManager.GetString("ProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote to Admin.
        /// </summary>
        internal static string PromoteToAdmin {
            get {
                return ResourceManager.GetString("PromoteToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Consumption (W).
        /// </summary>
        internal static string PwrConsumptionThresholdLabel {
            get {
                return ResourceManager.GetString("PwrConsumptionThresholdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-Time Status.
        /// </summary>
        internal static string RealTimeStatus {
            get {
                return ResourceManager.GetString("RealTimeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting to login....
        /// </summary>
        internal static string RedirectingToLogin {
            get {
                return ResourceManager.GetString("RedirectingToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Account.
        /// </summary>
        internal static string RegisterAccount {
            get {
                return ResourceManager.GetString("RegisterAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed: Username or email already exists.
        /// </summary>
        internal static string RegisterError {
            get {
                return ResourceManager.GetString("RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering....
        /// </summary>
        internal static string Registering {
            get {
                return ResourceManager.GetString("Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successful! Please login.
        /// </summary>
        internal static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Registration.
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration is currently disabled..
        /// </summary>
        internal static string RegistrationDisabled {
            get {
                return ResourceManager.GetString("RegistrationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset password..
        /// </summary>
        internal static string ResetPasswordFailed {
            get {
                return ResourceManager.GetString("ResetPasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully..
        /// </summary>
        internal static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        internal static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule added successfully..
        /// </summary>
        internal static string RuleAdded {
            get {
                return ResourceManager.GetString("RuleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add rule..
        /// </summary>
        internal static string RuleAddFailed {
            get {
                return ResourceManager.GetString("RuleAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule deleted..
        /// </summary>
        internal static string RuleDeleted {
            get {
                return ResourceManager.GetString("RuleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete rule..
        /// </summary>
        internal static string RuleDeleteFailed {
            get {
                return ResourceManager.GetString("RuleDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Enabled.
        /// </summary>
        internal static string RuleEnabled {
            get {
                return ResourceManager.GetString("RuleEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Name.
        /// </summary>
        internal static string RuleName {
            get {
                return ResourceManager.GetString("RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move rule further..
        /// </summary>
        internal static string RuleOrderMoveFailed {
            get {
                return ResourceManager.GetString("RuleOrderMoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule order updated..
        /// </summary>
        internal static string RuleOrderUpdated {
            get {
                return ResourceManager.GetString("RuleOrderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule saved successfully!.
        /// </summary>
        internal static string RuleSavedSuccess {
            get {
                return ResourceManager.GetString("RuleSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the rule..
        /// </summary>
        internal static string RuleSaveFailed {
            get {
                return ResourceManager.GetString("RuleSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule status updated..
        /// </summary>
        internal static string RuleStatusUpdated {
            get {
                return ResourceManager.GetString("RuleStatusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule updated successfully..
        /// </summary>
        internal static string RuleUpdated {
            get {
                return ResourceManager.GetString("RuleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Configuration.
        /// </summary>
        internal static string SaveConfiguration {
            get {
                return ResourceManager.GetString("SaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration saved successfully!.
        /// </summary>
        internal static string SaveConfigurationSuccess {
            get {
                return ResourceManager.GetString("SaveConfigurationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDR List Output:.
        /// </summary>
        internal static string SdrListOutput {
            get {
                return ResourceManager.GetString("SdrListOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Log File.
        /// </summary>
        internal static string SelectLogFile {
            get {
                return ResourceManager.GetString("SelectLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Mode.
        /// </summary>
        internal static string SelectMode {
            get {
                return ResourceManager.GetString("SelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        internal static string Sensor {
            get {
                return ResourceManager.GetString("Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Data Retention (Days).
        /// </summary>
        internal static string SensorDataRetentionDays {
            get {
                return ResourceManager.GetString("SensorDataRetentionDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set all fans speed to {0}%.
        /// </summary>
        internal static string SetAllFansSpeedTo {
            get {
                return ResourceManager.GetString("SetAllFansSpeedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully!.
        /// </summary>
        internal static string SettingsSavedSuccess {
            get {
                return ResourceManager.GetString("SettingsSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save settings..
        /// </summary>
        internal static string SettingsSaveFailed {
            get {
                return ResourceManager.GetString("SettingsSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to auto control fan mode succeed..
        /// </summary>
        internal static string SetToAutoControlFanModeSucceed {
            get {
                return ResourceManager.GetString("SetToAutoControlFanModeSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to manual control fan mode succeed..
        /// </summary>
        internal static string SetToManualControlFanModeSucceed {
            get {
                return ResourceManager.GetString("SetToManualControlFanModeSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Control Rules.
        /// </summary>
        internal static string SmartControlRules {
            get {
                return ResourceManager.GetString("SmartControlRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart (Rule-Based).
        /// </summary>
        internal static string SmartRuleBased {
            get {
                return ResourceManager.GetString("SmartRuleBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp Host.
        /// </summary>
        internal static string SmtpHost {
            get {
                return ResourceManager.GetString("SmtpHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp Password.
        /// </summary>
        internal static string SmtpPassword {
            get {
                return ResourceManager.GetString("SmtpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp Port.
        /// </summary>
        internal static string SmtpPort {
            get {
                return ResourceManager.GetString("SmtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp User.
        /// </summary>
        internal static string SmtpUser {
            get {
                return ResourceManager.GetString("SmtpUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        internal static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Fans.
        /// </summary>
        internal static string TargetFans {
            get {
                return ResourceManager.GetString("TargetFans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Fan Speed.
        /// </summary>
        internal static string TargetFanSpeed {
            get {
                return ResourceManager.GetString("TargetFanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Fan Speed (%).
        /// </summary>
        internal static string TargetFanSpeedLabel {
            get {
                return ResourceManager.GetString("TargetFanSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target fan speed required..
        /// </summary>
        internal static string TargetFanSpeedRequiredError {
            get {
                return ResourceManager.GetString("TargetFanSpeedRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one target fan..
        /// </summary>
        internal static string TargetFansRequiredError {
            get {
                return ResourceManager.GetString("TargetFansRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target speed is required!.
        /// </summary>
        internal static string TargetSpeedRequiredError {
            get {
                return ResourceManager.GetString("TargetSpeedRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Bot Token.
        /// </summary>
        internal static string TelegramBotToken {
            get {
                return ResourceManager.GetString("TelegramBotToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Chat ID.
        /// </summary>
        internal static string TelegramChatID {
            get {
                return ResourceManager.GetString("TelegramChatID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Settings.
        /// </summary>
        internal static string TelegramSettings {
            get {
                return ResourceManager.GetString("TelegramSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature History.
        /// </summary>
        internal static string TemperatureHistory {
            get {
                return ResourceManager.GetString("TemperatureHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use variables: {RuleName}, {ConditionsSummary}.
        /// </summary>
        internal static string TemplateVariables {
            get {
                return ResourceManager.GetString("TemplateVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string TestButton {
            get {
                return ResourceManager.GetString("TestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you can close this, the basic dialog mechanism is working..
        /// </summary>
        internal static string TestDialogContent {
            get {
                return ResourceManager.GetString("TestDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Dialog.
        /// </summary>
        internal static string TestDialogTitle {
            get {
                return ResourceManager.GetString("TestDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send test notification. Please check your settings and the application logs..
        /// </summary>
        internal static string TestFailedMessage {
            get {
                return ResourceManager.GetString("TestFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a test notification from FanX..
        /// </summary>
        internal static string TestMessageBody {
            get {
                return ResourceManager.GetString("TestMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Notification.
        /// </summary>
        internal static string TestMessageTitle {
            get {
                return ResourceManager.GetString("TestMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test notification sent successfully!.
        /// </summary>
        internal static string TestSuccessMessage {
            get {
                return ResourceManager.GetString("TestSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        internal static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred when getting sensor data..
        /// </summary>
        internal static string UnknownErrorWhenGetSensorData {
            get {
                return ResourceManager.GetString("UnknownErrorWhenGetSensorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update user..
        /// </summary>
        internal static string UpdateUserFailed {
            get {
                return ResourceManager.GetString("UpdateUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully..
        /// </summary>
        internal static string UpdateUserSuccess {
            get {
                return ResourceManager.GetString("UpdateUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        internal static string UserAccount {
            get {
                return ResourceManager.GetString("UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        internal static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Log.
        /// </summary>
        internal static string ViewLog {
            get {
                return ResourceManager.GetString("ViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Body Template.
        /// </summary>
        internal static string WebhookBodyTemplate {
            get {
                return ResourceManager.GetString("WebhookBodyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Method.
        /// </summary>
        internal static string WebhookRequestMethod {
            get {
                return ResourceManager.GetString("WebhookRequestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook Settings.
        /// </summary>
        internal static string WebhookSettings {
            get {
                return ResourceManager.GetString("WebhookSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {Title} and {Message} as placeholders. The content will be sent as JSON..
        /// </summary>
        internal static string WebhookTemplateHelpText {
            get {
                return ResourceManager.GetString("WebhookTemplateHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook URL.
        /// </summary>
        internal static string WebhookURL {
            get {
                return ResourceManager.GetString("WebhookURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeCom Bot Key.
        /// </summary>
        internal static string WeComBotKey {
            get {
                return ResourceManager.GetString("WeComBotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeCom Bot Settings.
        /// </summary>
        internal static string WeComBotSettings {
            get {
                return ResourceManager.GetString("WeComBotSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back, {0}!.
        /// </summary>
        internal static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a login authentication example application built with Blazor, MudBlazor, SQLite and SqlSugar..
        /// </summary>
        internal static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
